services:
  api:
    image: prasheshadk/ecommerce-shipping-delay-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    image: prasheshadk/ecommerce-shipping-delay-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000/predict
    depends_on:
      - api
